### ISSUE TITLE
[Umbrella Issue] Implements equivalences for kubectl commands

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1072]
### Basic commands
- [x] kubectl exec: though we already have helper class `Exec`, a kubectl wrapper can be more user-friendly
- [x] kubectl logs: \<ditto\>
- [x] kubectl port-forward: \<ditto\>
- [x] kubectl cp: \<ditto\>
- [x] kubectl scale: https://github.com/kubernetes-client/java/issues/968
- [ ] kubectl rollout: https://github.com/kubernetes-client/java/issues/599
- [x] kubectl annotate
- [x] kubectl create https://github.com/kubernetes-client/java/pull/1187

### Cluster/Node management
- [x] kubectl taint: https://github.com/kubernetes-client/java/issues/517
- [x] kubectl drain: https://github.com/kubernetes-client/java/issues/1069
- [x] kubectl cordon/uncordon: https://github.com/kubernetes-client/java/issues/306
- [x] kubectl top: https://github.com/kubernetes-client/java/issues/892

### Advanced commands
- [x] kubectl patch: we have `PatchUtils` documented on README, however a `Kubectl.patch(..)` be easier for developers to find..
- [x] https://github.com/kubernetes-client/java/pull/1078 kubectl label/annotate: obviously a common usecase
- [x] kubectl version: TBD
- [x] kubectl api-resources: cluster api discovery is necessary for some usecases

**Comment by sarveshkaushal** [comment]
Thanks for providing the list. I am confused on where to implement these. I generated code using code-gen repo. But don't see new changes. Some pointers to existing implementation for reference will help.

**Comment by brendandburns** [comment]
@sarveshkaushal the hand-written code for most of these are located here:

https://github.com/kubernetes-client/java/tree/master/util/src/main/java/io/kubernetes/client

You can add new hand-written utility classes (e.g. `Drain.java`) there.

**Comment by brendandburns** [comment]
(and thanks!)

**Comment by sarveshkaushal** [comment]
> @sarveshkaushal the hand-written code for most of these are located here:
> 
> https://github.com/kubernetes-client/java/tree/master/util/src/main/java/io/kubernetes/client
> 
> You can add new hand-written utility classes (e.g. `Drain.java`) there.

Thanks I will take a look at it.

**Comment by Fly0905** [comment]
> Drain.java

Where is Drain.java ? Is Implements equivalences for kubectl drain

**Comment by sarveshkaushal** [comment]
You can create it.

**Comment by sarveshkaushal** [comment]
@brendandburns @yue9944882 I have implemented a utility class. But want to make sure this is acceptable:
```
public class VersionUtil {
  private ApiClient apiClient;
  private VersionApi versionApi;

  public VersionUtil() {
    this(Configuration.getDefaultApiClient());
  }

  public VersionUtil(ApiClient apiClient) {
    this.apiClient = apiClient;
    this.versionApi = new VersionApi();
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public VersionInfo getVersion() throws ApiException {
    return versionApi.getCode();
  }
}
```

**Comment by yue9944882** [comment]
i started `kubectl label` in https://github.com/kubernetes-client/java/pull/1078 as this subcommand is a low-hanging fruit. we will be accepting more subcommands after we agreed on the structure/framework.

**Comment by brendandburns** [comment]
@sarveshkaushal for `version` you need to make a call to the server in order to get the version that the server is running. I don't see your code making that network API call.

**Comment by brendandburns** [comment]
@yue9944882 I'm going to start working on `kubectl scale`

**Comment by brendandburns** [comment]
@yue9944882 I'm going to start working on `kubectl exec`

**Comment by brendandburns** [comment]
I'm going to start working on `kubectl logs`

**Comment by brendandburns** [comment]
I'm going to start working on `kubectl port-forward`

**Comment by brendandburns** [comment]
I'm going to start working on `kubectl cp`

**Comment by zhamdoctor** [comment]
> I'm going to start working on `kubectl cp`

budy,what about `kubectl rollout`,was it worked out or had anthing alternative.

**Comment by yue9944882** [comment]
@zhamdoctor it's tracked in the list and i believe we will be seeing it published in the next major release

**Comment by zhamdoctor** [comment]
> @zhamdoctor it's tracked in the list and i believe we will be seeing it published in the next major release

I saw someone said updating keyword `deploymentSpec.rollbackTo` and updating deployment can achieve this goal acting like `kubectl rollout undo` ,was it  practicable only for `undo` but not for `history,status`?

**Comment by brendandburns** [comment]
I'm going to start on `kubectl drain`

**Comment by SameeraGrandhi** [comment]
I would like to take up some other equivalent commands , can I work on  `kubectl api-resources`

**Comment by brendandburns** [comment]
@SameeraGrandhi sounds great, we'd love to have the help. The only thing we're currently missing from the list above is KubectlRollout. That command is semi-complicated, but the go source to start from is here:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/rollout/rollout.go

Let us know if you need assistance.

If there are other Kubectl commands that you would rather add, that we don't already have, feel free.

**Comment by SameeraGrandhi** [comment]
Thanks @brendanburns , will work on `kubectl rollout` first and take others once this is completed.

**Comment by SameeraGrandhi** [comment]
@brendanburns , rollout undo is making multiple get calls to each of the apigroup from the list 
`GET https://xx.xx.xx.xx/apis?timeout=32s` 

Why does it have to call all apigroups when we are dealing only with few resource set [daemonsets,deployments,statefulsets] ?
Is there anything I'm missing here ? Can you give me some leads on this ?

**Comment by brendandburns** [comment]
Is this from `kubectl`? Kubectl loads all of the APIs from the API discovery endpoint when it starts. It caches these locally, so this should only happen on a clean kubectl.

Regardless, I don't think that's part of implementing rollout for this library, you can focus on the changes that it makes to the `Deployment` object.

**Comment by SameeraGrandhi** [comment]
@brendanburns Can I first push the outline of this command framework and then add the business logic of them ?

**Comment by brendandburns** [comment]
@SameeraGrandhi feel free to send a work-in-progress PR (put "WIP" in the title and it will get automatically labelled as such) and we can review and iterate in the PR.

Thanks!

**Comment by Sryther** [comment]
After digging a little, the `rollout restart` command performs two actions:

1. Patch the resource with the following:
```json
{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"<date>"}}}}}
```
2. Add or replace an item in the `metadata.managedFields` array:
```yaml
- manager: kubectl-rollout
  operation: Update
  apiVersion: apps/v1
  time: '<date>'
  fieldsType: FieldsV1
  fieldsV1:
  'f:spec':
    'f:template':
      'f:metadata':
        'f:annotations':
          'f:kubectl.kubernetes.io/restartedAt': {}
```

`<date>` is the ISO formatted actual date.

I think the second step is not a mandatory.
You can find the API calls by calling `kubectl rollout restart <anything> --v 9`.

For a personal project, I tried an approach using the `KubectlPatch` resource builder (it's not clean at the moment ^^):

```java
public static <ApiType extends KubernetesObject> KubectlPatch<ApiType> restart(Class<ApiType> clazz) {
    String date = Instant.now().truncatedTo(ChronoUnit.MINUTES).toString();

    // Should look like this:
    // {"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"<date>"}}}}}
    JSONObject restartedObject = new JSONObject().put("kubectl.kubernetes.io/restartedAt", date);
    JSONObject annotationsObject = new JSONObject().put("annotations", restartedObject);
    JSONObject metadataObject = new JSONObject().put("metadata", annotationsObject);
    JSONObject templateObject = new JSONObject().put("template", metadataObject);
    JSONObject patchJson = new JSONObject().put("spec", templateObject);

    V1Patch patch = new V1Patch(patchJson.toString());

    return (KubectlPatch<ApiType>) Kubectl.patch(clazz)
        .patchContent(patch)
        .patchType(V1Patch.PATCH_FORMAT_STRATEGIC_MERGE_PATCH);
}
```

Note that this method won't let you have a proper result for the `rollout history` command. I think the `rollout history` command uses the `managedFields` values.
