### ISSUE TITLE
[Umbrella Issue] SDK Observability

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1073]
this issue tracks observability enhancements upon the existing utilities.. e.g. integration w/ open-telemetry or other third-party monitoring frameworks:
 
- Metrics plumbing
  - [ ] (blocked on the progress on open-telemetry metrics SDK )
- Tracing plumbing
  - [x] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/651: Essential open-telemetry integration for basic client capabilities
  - [ ] Tracing support on informer/controller framework

**Comment by brendandburns** [comment]
might be worth adding Prometheus metrics also (or at least optional Prometheus metrics)
