### ISSUE TITLE
[Umbrella Issue] Many tests use Thread.sleep instead of synchronization primitives

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1223]
Many of our tests simply have a `Thread.sleep(duration)` when testing multi-threaded code. This is inherently flaky.

Instead we should use synchronization classes (generally `Semaphore`) to synchronized the tests which is both faster in the general case and not flaky in the extreme case.

See for instance #1218 and #1219

**Comment by brendandburns** [comment]
- [ ] util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
- [ ] util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
- [ ] util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
- [ ] util/src/test/java/io/kubernetes/client/CopyTest.java
- [ ] util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultWorkQueueTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
- [ ] util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
- [ ] util/src/test/java/io/kubernetes/client/PortForwardTest.java
- [ ] util/src/test/java/io/kubernetes/client/AttachTest.java
- [ ] util/src/test/java/io/kubernetes/client/ExecTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiterTest.java
- [ ] spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
- [ ] spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
- [ ] extended/src/test/java/io/kubernetes/client/extended/event/EventCorrelatorTest.java

**Comment by yue9944882** [comment]
@brendandburns thanks for sorting out these potentially flaking tests.. will fix them later!

/assign

**Comment by sarveshkaushal** [comment]
I would like to help :-)

**Comment by brendandburns** [comment]
@sarveshkaushal we'd welcome the help. In most cases the Thread.sleep(foo) is to wait for some other thread to complete it's work. Instead, we should create a `Semaphore`, then `acquire()` one or more permits for the executions we're waiting for, and then `release()` them in the Thread, then attempt to `acquire()` in the test thread to implement the wait.

See an example PR #1219

**Comment by Priya103** [comment]
If still available I would like to contribute

**Comment by Vishal-thakur-01** [comment]
well i am new to java and i would like to get in touch with you guys and try to do my best in solving all the issues hope you all will understand my curiosity and get in touch with me and help me to grow and learn.........

**Comment by Vyom-Yadav** [comment]
@brendandburns I have one doubt, I was working on ` util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java`, particularly on:
https://github.com/kubernetes-client/java/blob/536f72556899a5a951a9d1d000f4b5073429e017/util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java#L27-L60

I can create a semaphore and acquire it, blocking the main thread, but how will I release so that blocked main thread will continue the execution, I looked at many tests, facing similar problem in many of them.

**Comment by vinayak912002** [comment]
Hey, Iwant to start contributing to this project can someone please tell me what should i learn to do that?

**Comment by vinayak912002** [comment]
what are the things I need to learn in order to start contributiing to this project?

**Comment by Mohdcode** [comment]
> what are the things I need to learn to start contributing to this project?

DSA, API, and Kubernetes  or just contribute by documentation correction or making better changes

**Comment by Vyom-Yadav** [comment]
@brendandburns ping

**Comment by abhinavvrm2020** [comment]
@brendandburns Is this issue still open. I would like to fix these tests.

**Comment by priyanshuvishwakarma273403** [comment]
Hi @maintainer,
I would like to work on this issue. Could you please assign it to me?
